// Admin shell. The heavy admin client and KuroEditor are NOT embedded here — they are
// served as separate hashed assets under {base}/_admin/ (see src/asset-serve.ts).
// ADMIN_APP_HASH / KE_VERSION are generated by scripts/build-admin.js into ./admin-assets.
import { ADMIN_APP_HASH, KE_VERSION } from "./admin-assets";

export function adminHtml(
  options: { accessAdminUrl?: string; base?: string } = {},
): string {
  const accessAdminUrl = options.accessAdminUrl || "/kurocms/admin";
  const base = options.base ?? "";
  return `<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/svg+xml" href="https://kuro.boo/favicon.svg" />
    <title>KuroCMS Admin</title>
    <style>
      @layer properties, theme, base, kuroeditor, components, utilities, kurocms;
      @layer kurocms {
      :root {
        --bg: #ffffff;
        --surface: #ffffff;
        --surface-2: #f0f9ff;
        --surface-3: #e0f2fe;
        --line: #e2e8f0;
        --line-strong: #cbd5e1;
        --ink: #1e293b;
        --muted: #64748b;
        --heading: #f97316;
        --theme-accent: #06b6d4;
        --theme-sidebar: #ffffff;
        --theme-main-pane: #ffffff;
        --accent: var(--theme-accent);
        --accent-2: #0284c7;
        --accent-3: #f59e0b;
        --accent-soft: #ecfeff;
        --teal-soft: #ecfeff;
        --danger: #ef4444;
        --shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.05);
        --radius: 12px;
        --nav-active-bg: var(--accent);
        --nav-active-fg: #ffffff;
        --field-bg: #ffffff;
        --field-ink: #1e293b;
        --nav-link: #64748b;
        font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      }
      [data-theme="dark"] {
        --bg: #0f172a;
        --surface: #1e293b;
        --surface-2: #334155;
        --surface-3: #475569;
        --line: #334155;
        --line-strong: #475569;
        --ink: #f1f5f9;
        --muted: #94a3b8;
        --heading: #fb923c;
        --theme-sidebar: #0f172a;
        --theme-main-pane: #0f172a;
        --accent-soft: #083344;
        --teal-soft: #083344;
        --shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.2), 0 10px 10px -5px rgba(0, 0, 0, 0.1);
        --nav-active-bg: var(--accent);
        --nav-active-fg: #ffffff;
        --field-bg: #0f172a;
        --field-ink: #f1f5f9;
        --nav-link: #94a3b8;
      }
      * { box-sizing: border-box; }
      html { scroll-padding-bottom: 70px; }
      body { margin: 0; background: var(--theme-main-pane); color: var(--ink); overflow-x: hidden; }
      a { color: inherit; text-decoration: none; }
      .app { display: grid; grid-template-columns: var(--sidebar-w, 210px) 1fr; min-height: 100vh; }
      /* Draggable divider between the sidebar and the workspace. Invisible until
         hovered/dragged; updates --sidebar-w (persisted in localStorage). */
      .sidebarResizer { position: fixed; top: 0; bottom: 0; left: var(--sidebar-w, 210px); width: 9px; margin-left: -5px; cursor: col-resize; z-index: 60; }
      .sidebarResizer::after { content: ""; position: absolute; top: 0; bottom: 0; left: 50%; width: 2px; transform: translateX(-50%); background: transparent; transition: background 140ms ease; }
      .sidebarResizer:hover::after, .sidebarResizer.dragging::after { background: var(--accent); }
      body.sidebarResizing { user-select: none; cursor: col-resize; }
      aside { position: sticky; top: 0; height: 100vh; border-right: 1px solid var(--line); background: var(--theme-sidebar); color: var(--ink); padding: 24px 18px; transition: width 220ms ease; display: flex; flex-direction: column; z-index: 50; }
      .brand { display: grid; grid-template-columns: 40px 1fr; gap: 12px; align-items: center; margin-bottom: 30px; }
      .brandMark { display: grid; place-items: center; width: 40px; height: 40px; border-radius: 10px; background: var(--heading); color: #fff; font-weight: 800; flex-shrink: 0; }
      aside h1 { margin: 0; font-size: 18px; line-height: 1.1; letter-spacing: -0.02em; color: var(--heading) !important; font-weight: 800; display: flex; align-items: baseline; gap: 2px; }
      .brandAccent { color: var(--ink); opacity: 0.6; font-weight: 600; }
      .brandSub { color: var(--muted); font-size: 11px; margin-top: 4px; font-weight: 600; }
      .sidebarBody { flex: 1; min-height: 0; overflow: auto; margin: 0 -6px; padding: 0 6px; }
      .sidebarFooter { display: grid; gap: 6px; padding-top: 16px; margin-top: 16px; border-top: 1px solid var(--line); }
      nav.sidebarNav { display: grid; gap: 4px; }
      nav.sidebarNav a { position: relative; display: flex; align-items: center; gap: 11px; min-height: 42px; padding: 10px 12px; border-radius: 10px; color: var(--nav-link); font-size: 14px; font-weight: 600; transition: all 150ms ease; }
      nav.sidebarNav a:hover { background: var(--surface-2); color: var(--ink); }
      nav.sidebarNav a.active { background: var(--nav-active-bg); color: var(--nav-active-fg); font-weight: 700; }
      nav.sidebarNav svg { flex-shrink: 0; width: 18px; height: 18px; opacity: 0.7; }
      nav.sidebarNav a.active svg { color: #ffffff; opacity: 1; }
      main { padding: 34px; max-width: 1440px; width: 100%; min-height: 100vh; background: var(--theme-main-pane); overflow-x: hidden; box-sizing: border-box; min-width: 0; }
      .initialLoader { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 60vh; gap: 18px; }
      .initialLoaderSpinner { width: 38px; height: 38px; border: 3px solid var(--line); border-top-color: var(--accent); border-radius: 50%; animation: kcmsSpinInit 0.75s linear infinite; }
      .initialLoaderLabel { font-size: 13px; color: var(--muted); font-weight: 600; letter-spacing: 0.04em; }
      @keyframes kcmsSpinInit { to { transform: rotate(360deg); } }
      header { display: flex; justify-content: space-between; align-items: flex-start; gap: 20px; margin-bottom: 28px; padding: 0; border: 0; background: transparent; }
      h2 { margin: 0; font-size: 32px; letter-spacing: -0.02em; line-height: 1.1; color: var(--heading); font-weight: 800; }
      h3 { margin: 0 0 12px; color: var(--heading); font-size: 18px; font-weight: 750; }
      .muted { color: var(--muted); }
      .panel { min-width: 0; background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius); padding: 22px; box-shadow: 0 12px 30px rgba(20,24,32,0.04); }
      .grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; }
      .grid.two { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .grid.four { grid-template-columns: repeat(4, minmax(0, 1fr)); }
      .stack { display: grid; gap: 18px; }
      .stack > * { min-width: 0; }
      .profileGrid { align-items: start; }
      label { display: grid; gap: 7px; font-size: 12px; color: var(--muted); font-weight: 700; min-width: 0; }
      input, select, textarea { width: 100%; min-width: 0; border: 1px solid var(--line); border-radius: 8px; padding: 11px 12px; font: inherit; background: var(--field-bg); color: var(--field-ink); outline: none; box-sizing: border-box; }
      input[readonly], input:disabled {
        background: var(--surface-2);
        color: var(--ink);
        border-style: dashed;
        cursor: not-allowed;
      }
      input::placeholder, textarea::placeholder { color: color-mix(in srgb, var(--muted) 72%, transparent); }
      input:focus, select:focus, textarea:focus { border-color: var(--accent); box-shadow: 0 0 0 3px rgba(21,122,110,0.14); }
      textarea { min-height: 240px; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
      .editorHost { border: 1px solid var(--line); border-radius: 10px; overflow: visible; background: var(--surface); }
      .editorHost .sun-editor { border: 0; overflow: visible; }
      .editorHost .se-wrapper { min-height: 280px; }
      .editorHost .se-toolbar { background: var(--surface-2); border-bottom: 1px solid var(--line); }
      .editorHost .se-wrapper-inner { background: var(--surface); }
      .editorHost .se-resizing-bar { display: none !important; }
      .editorHost .sun-editor-editable { background: var(--surface); color: var(--ink); }
      .editorHost .sun-editor-editable p,
      .editorHost .sun-editor-editable div,
      .editorHost .sun-editor-editable span,
      .editorHost .sun-editor-editable li,
      .editorHost .sun-editor-editable td,
      .editorHost .sun-editor-editable th {
        color: var(--ink);
      }
      .simpleEditorHost { position: relative; padding: 12px; min-height: 280px; }
      .simpleEditorArea {
        min-height: 240px;
        color: var(--ink);
        outline: none;
        line-height: 1.7;
      }
      .simpleEditorArea:empty::before { content: "Type article body..."; color: var(--muted); }
      .simpleBalloon {
        position: absolute;
        display: none;
        gap: 6px;
        padding: 6px;
        border: 1px solid var(--line);
        border-radius: 8px;
        background: var(--surface);
        box-shadow: 0 10px 24px rgba(0, 0, 0, 0.18);
        z-index: 1200;
      }
      .simpleBalloon button {
        border: 1px solid var(--line);
        background: var(--surface-2);
        color: var(--ink);
        border-radius: 6px;
        padding: 6px 8px;
        font-size: 12px;
        font-weight: 700;
      }
      .licenseBox { max-height: 320px; overflow: auto; white-space: pre-wrap; border: 1px solid var(--line); border-radius: 7px; background: #231f1a; color: #f8efe2; padding: 14px; font: 12px/1.6 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
      .checkRow { display: flex; align-items: flex-start; gap: 9px; font-size: 14px; color: var(--ink); padding: 12px; border: 1px solid var(--line); border-radius: 7px; background: var(--surface-2); }
      .checkRow input { width: auto; margin-top: 4px; }
      .listPager { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-top: 16px; flex-wrap: wrap; }
      .listPager .pageSizeWrap { display: inline-flex; align-items: center; gap: 9px; font-size: 13px; font-weight: 600; color: var(--muted); }
      .listPager select { width: auto; height: 38px; padding: 0 12px; border-radius: 10px; border: 1px solid var(--line); background: var(--surface-2); color: var(--ink); font: inherit; font-size: 13px; font-weight: 600; cursor: pointer; transition: border-color .15s ease; }
      .listPager select:hover { border-color: var(--accent); }
      /* Segmented pill nav: shares the select's surface/line palette so the
         left (page size) and right (pager) sides read as a matched pair. */
      .pagerNav { display: inline-flex; align-items: center; gap: 2px; padding: 4px; border: 1px solid var(--line); border-radius: 12px; background: var(--surface-2); }
      .pagerBtn { display: inline-flex; align-items: center; justify-content: center; min-width: 30px; height: 30px; padding: 0 10px; border: 0; background: transparent; color: var(--muted); border-radius: 8px; cursor: pointer; font: inherit; font-size: 13px; font-weight: 600; line-height: 1; transition: background .15s ease, color .15s ease; }
      .pagerBtn:hover:not(:disabled):not(.active) { background: var(--surface-3); color: var(--ink); }
      .pagerBtn.active { background: var(--accent-soft); color: var(--accent); box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--accent) 45%, transparent); }
      .pagerBtn[data-page]:first-child, .pagerNav > .pagerBtn:last-child { font-size: 16px; color: var(--ink); }
      .pagerBtn:disabled { opacity: .3; cursor: default; }
      .pagerEllipsis { display: inline-flex; align-items: center; justify-content: center; min-width: 22px; height: 30px; color: var(--muted); }
      .colorRows { display: grid; gap: 10px; }
      .langRows { display: grid; gap: 10px; }
      .langRow { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 10px 12px; border: 1px solid var(--line); border-radius: 8px; background: var(--surface-2); }
      .langRow label { display: inline-flex; align-items: center; gap: 8px; margin: 0; font-size: 14px; font-weight: 600; color: var(--ink); }
      .langRow input[type="checkbox"] { width: 16px; height: 16px; margin: 0; }
      .colorItem { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 12px; border: 1px solid var(--line); border-radius: 7px; background: var(--surface-2); }
      .colorItem input[type="color"] {
        -webkit-appearance: none;
        appearance: none;
        width: 44px;
        height: 34px;
        padding: 2px;
        border: 1px solid var(--line);
        border-radius: 8px;
        background: transparent;
        cursor: pointer;
      }
      .colorItem input[type="color"]::-webkit-color-swatch-wrapper { padding: 0; }
      .colorItem input[type="color"]::-webkit-color-swatch { border: none; border-radius: 6px; }
      .colorItem input[type="color"]::-moz-color-swatch { border: none; border-radius: 6px; }
      .colorTitle { font-weight: 750; color: var(--ink); }
      .colorHelp { color: var(--muted); font-size: 12px; margin-top: 2px; }
      .settingsTabBar { display: flex; gap: 2px; border-bottom: 2px solid var(--accent); padding-bottom: 0; margin-bottom: 0; }
      .settingsTab { background: rgba(21,122,110,.10); border: 1.5px solid var(--accent); border-bottom: none; color: var(--accent); padding: 8px 18px; font: inherit; font-size: 14px; font-weight: 700; cursor: pointer; border-radius: 8px 8px 0 0; opacity: .45; transition: opacity .15s; }
      .settingsTab:hover { opacity: .7; }
      .settingsTab.active { background: var(--accent); color: #fff; opacity: 1; margin-bottom: -2px; border-bottom: 2px solid var(--accent); }
      .settingsPanel { animation: fadeIn 0.15s ease; width:100%; box-sizing:border-box; }
      .importSwitcher { display:flex; background:var(--surface-3); border:1px solid var(--line); border-radius:10px; padding:4px; gap:4px; }
      .importSwitcher .importSwitch { flex:1; padding:9px 16px; font:inherit; font-size:14px; font-weight:600; border:none; border-radius:7px; cursor:pointer; transition:all 0.15s; }
      .importSwitcher .importSwitch:not(.active) { background:transparent; color:var(--muted); }
      .importSwitcher .importSwitch:hover:not(.active) { background:var(--surface-2); color:var(--ink); }
      .importSwitcher .importSwitch.active { background:var(--accent); color:#fff; box-shadow:0 1px 4px rgba(0,0,0,.25); }
      .settingsPanel > .panel, .settingsPanel > .panel.stack { border-radius: 0 !important; border-top: none !important; }
      .settingsPanel > .stack > .panel:first-child { border-radius: 0 !important; border-top: none !important; }
      .articleEditorPage { padding-bottom: 80px; }
      .strapiRow { overflow: hidden !important; }
      .strapiRow:hover { background: var(--surface-2); }
      .articleBottomBar { position: fixed; bottom: 0; left: calc(264px + 5%); right: 5%; min-height: 72px; background: var(--surface); border: 1.5px solid var(--line-strong); border-bottom: none; border-radius: 12px 12px 0 0; display: flex; align-items: center; justify-content: space-between; padding: 12px 20px; z-index: 500; box-shadow: 0 -4px 20px rgba(0,0,0,.10); gap: 16px; flex-wrap: wrap; }
      @media(max-width:860px){ .articleBottomBar { left: 5%; right: 5%; } }
      /* Build-mode dropdown: opt out of the global "select{width:100%}" and the
         native arrow so the box auto-sizes to its widest option in any language
         (no clipping / no overlap) with a custom chevron in reserved padding. */
      .buildModeSelect { width: auto; min-width: 0; max-width: 100%; appearance: none; -webkit-appearance: none; -moz-appearance: none; height: 38px; padding: 0 32px 0 12px; font-size: 13px; font-weight: 600; border-radius: 10px; border: 1px solid var(--line); background-color: var(--surface-2); color: var(--ink); cursor: pointer; background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23888888' stroke-width='2.2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E"); background-repeat: no-repeat; background-position: right 12px center; transition: border-color .15s ease; }
      .buildModeSelect:hover { border-color: var(--accent); }
      .articleTopGrid { background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius) var(--radius) 0 0; display: grid; grid-template-columns: 2fr 1fr; align-items: stretch; }
      .articleCoverArea { padding: 14px 16px; display: flex; flex-direction: column; gap: 10px; border-right: 1px solid var(--line); }
      .articleCoverBox { aspect-ratio: 3/1; width: 100%; border: 2px dashed var(--line); border-radius: 8px; overflow: hidden; background: var(--surface-2); display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 4px; transition: border-color .15s, background .15s; }
      .articleCoverBox img { width: 100%; height: 100%; object-fit: cover; }
      .articleCoverBox.dragover { border-color: var(--accent); background: rgba(21,122,110,.08); }
      .articleCoverBox.r2Disabled { opacity: 0.5; cursor: not-allowed; }
      .articleCoverActions { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
      .articleMetaPanel { padding: 14px 16px; display: flex; flex-direction: column; gap: 10px; overflow-y: auto; }
      .articleField { background: var(--surface); border: 1px solid var(--line); border-top: none; padding: 12px 16px; }
      .articleBodyWrap { background: var(--surface); border: 1px solid var(--line); border-top: none; padding: 12px 16px; border-radius: 0 0 var(--radius) var(--radius); }
      .arKeToolbarSlot { display: flex; align-items: center; flex: 1; min-width: 0; }
      /* KuroEditor slotted buttons — KuroEditor resets its own styles in slotted mode, so style freely here */
      .arKeToolbarSlot .kuro-mmenu__btn { font-size: 12px; padding: 4px 8px; border-radius: 6px; color: var(--muted); background: none; border: none; cursor: pointer; }
      .arKeToolbarSlot .kuro-mmenu__btn:hover, .arKeToolbarSlot .kuro-mmenu__btn--active { background: var(--surface-2); color: var(--ink); }
      .statusBadge { display: inline-flex; align-items: center; gap: 5px; padding: 3px 12px; border-radius: 20px; font-size: 12px; font-weight: 700; }
      .statusDraft { background: rgba(120,120,120,.12); color: var(--muted); }
      .statusPublished { background: rgba(21,122,110,.12); color: var(--accent); }
      .statusHidden { background: rgba(239,68,68,.12); color: var(--danger); }
      .artMeta2 { font-size: 11px; color: var(--muted); }
      .artsToolbar { display: flex; gap: 8px; align-items: center; margin-bottom: 8px; width: 100%; box-sizing: border-box; overflow: hidden; }
      .artTitleLink { font-weight: 700; font-size: 13px; color: var(--ink); text-decoration: none; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 100%; }
      .artTitleLink:hover { color: var(--accent); }
      /* Tight slug chip: hugs the slug text, small font, subtle frame.
         !important overrides the generic accent button rule below (same pattern
         as .artModeBtn / .rowActions button), which otherwise wins on specificity. */
      .artSlugCode { display: inline-block; max-width: 100%; margin-top: 3px; padding: 1px 6px !important; font-size: 10px; line-height: 1.5; color: var(--muted) !important; background: var(--surface-3) !important; border: 1px solid var(--line) !important; border-radius: 4px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: middle; }
      button.artSlugCode { width: auto !important; box-shadow: none !important; font-weight: 400 !important; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; text-align: left; cursor: copy; }
      button.artSlugCode:hover { color: var(--accent) !important; border-color: var(--accent) !important; background: var(--surface-3) !important; }
      button.artSlugCode:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
      .artTypeCats { display: flex; align-items: center; gap: 5px; flex-wrap: wrap; margin-top: 6px; min-height: 20px; }
      .artListType { display: inline-flex; align-items: center; max-width: 160px; padding: 2px 7px; border-radius: 5px; background: var(--surface-3); color: var(--muted); font-size: 11px; font-weight: 700; line-height: 1.35; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
      .artListCat { display: inline-flex; align-items: center; max-width: 180px; padding: 2px 8px; border-radius: 12px; background: rgba(21,122,110,.10); color: var(--accent); font-size: 11px; font-weight: 700; line-height: 1.35; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
      .snsStatusList { display: grid; gap: 3px; min-width: 118px; }
      .snsStatusLine { display: grid; grid-template-columns: 58px max-content; align-items: center; gap: 7px; font-size: 11px; line-height: 1.3; }
      .snsStatusName { color: var(--muted); font-weight: 800; }
      .snsStatusValue { font-weight: 800; }
      .snsStatusLine.posted .snsStatusValue { color: var(--accent); }
      .snsStatusLine.unposted .snsStatusValue { color: var(--muted); }
      button.snsPostBtn { padding: 2px 12px !important; font-size: 11px !important; font-weight: 800; border-radius: 999px; background: var(--accent); color: #fff; border: 0; cursor: pointer; line-height: 1.4; justify-self: start; }
      button.snsPostBtn:hover { filter: brightness(0.95); }
      button.snsPostBtn:disabled { opacity: 0.5; cursor: not-allowed; }
      .snsStatusMobile { margin: 8px 0; padding: 8px 10px; border: 1px solid var(--line); border-radius: 7px; background: var(--surface-2); }
      .catTag { display: inline-flex; align-items: center; gap: 3px; background: rgba(21,122,110,.10); color: var(--accent); border-radius: 12px; padding: 2px 8px 2px 10px; font-size: 12px; font-weight: 600; }
      .catTag button { display: inline-flex; align-items: center; justify-content: center; width: 14px; height: 14px; background: rgba(220,38,38,.65); border: none; border-radius: 50%; color: #fff; cursor: pointer; font-size: 9px; line-height: 1; padding: 0; flex-shrink: 0; }
      .catTag button:hover { background: rgb(220,38,38); }
      .catPickPopover { position: fixed; z-index: 2100; background: var(--surface); border: 1px solid var(--line); border-radius: 8px; box-shadow: var(--shadow); overflow-y: auto; min-width: 160px; }
      .catPickRow { padding: 9px 14px; cursor: pointer; font-size: 13px; white-space: nowrap; }
      .catPickRow:hover { background: var(--surface-2); }
      .autoSaveStatus { font-size: 12px; color: var(--muted); white-space: nowrap; }
      .autoSaveStatus.ok { color: var(--accent); }
      .autoSaveStatus.err { color: var(--danger); }
      .readonlyBanner { background: rgba(239,68,68,.07); border: 1px solid rgba(239,68,68,.2); color: var(--danger); padding: 8px 16px; border-radius: var(--radius); font-size: 13px; font-weight: 600; margin-bottom: 12px; display: flex; align-items: center; gap: 10px; }
      .fieldLabel { font-size: 12px; font-weight: 700; color: var(--muted); margin-bottom: 4px; display: block; }
      .articleEditorPage label { display: flex; flex-direction: column; gap: 4px; font-size: 13px; font-weight: 700; color: var(--muted); }
      .articleEditorPage label input, .articleEditorPage label textarea, .articleEditorPage label select { color: var(--ink); font-weight: 400; margin-top: 0; }
      .helpBtn { background: rgba(255,182,193,.18) !important; border: 1px solid rgba(220,80,110,.30) !important; color: rgb(185,50,80) !important; padding: 3px 9px !important; border-radius: 12px !important; font-size: 11px !important; font-weight: 600 !important; cursor: pointer; white-space: nowrap; transition: background .15s; flex-shrink: 0; box-shadow: none !important; }
      .helpBtn:hover { background: rgba(255,182,193,.38) !important; }
      .headerRight { display: flex; align-items: center; gap: 8px; flex: 0 0 auto; margin-left: auto; }
      .editorHeadActions { display: flex; flex-direction: column; align-items: flex-end; gap: 8px; flex: 0 0 auto; margin-left: auto; }
      .editorHeadTools { display: flex; align-items: center; gap: 8px; }
      .editorHeadBtnRow { display: flex; align-items: center; gap: 8px; }
      .editorDraftBtn { font-size: 13px !important; font-weight: 700 !important; padding: 8px 16px !important; white-space: nowrap; }
      .editorHeadBtn { font-size: 13px; padding: 7px 14px; white-space: nowrap; }
      .editorDelBtn { border: 2px solid var(--danger) !important; color: var(--danger) !important; background: transparent !important; box-shadow: none !important; }
      .editorBody { position: relative; }
      .editorLockOverlay { position: absolute; inset: 0; z-index: 5; background: rgba(100,105,120,.45); display: flex; align-items: flex-start; justify-content: center; padding-top: 60px; border-radius: var(--radius); }
      .editorLockOverlay span { font-weight: 700; font-size: 16px; color: #fff; background: rgba(15,20,30,.80); padding: 12px 22px; border-radius: 12px; text-align: center; max-width: 90%; box-shadow: 0 6px 24px rgba(0,0,0,.3); }
      .headerLocale { min-width: auto !important; width: auto; font-size: 12px; padding: 4px 8px; border-radius: 10px; cursor: pointer; }
      .helpDialog { position: fixed; top: 72px; right: clamp(8px, 2vw, 20px); width: clamp(0px, calc(100vw - 16px), 90vw); max-width: 90vw; max-height: calc(100vh - 96px); background: var(--surface); border: 1.5px solid var(--line-strong); border-radius: var(--radius); box-shadow: 0 10px 40px rgba(0,0,0,.18); z-index: 2000; display: flex; flex-direction: column; overflow: hidden; }
      .helpDialogHead { display: flex; align-items: center; justify-content: space-between; padding: 10px 14px; border-bottom: 1px solid var(--line); background: rgba(255,182,193,.10); flex-shrink: 0; cursor: move; }
      .helpDialogTitle { font-weight: 800; font-size: 14px; }
      .helpDialogClose { background: none; border: none; font-size: 20px; cursor: pointer; color: var(--muted); padding: 2px 6px; line-height: 1; border-radius: 6px; }
      .helpDialogClose:hover { background: var(--surface-2); }
      .helpDialogBody { overflow-y: auto; padding: 14px 16px; flex: 1; font-size: 13px; line-height: 1.75; }
      .helpSection { margin-bottom: 18px; }
      .helpSectionTitle { font-weight: 800; font-size: 12px; color: var(--accent); text-transform: uppercase; letter-spacing: .04em; margin-bottom: 5px; padding-bottom: 3px; border-bottom: 1px solid var(--line); }
      .helpLayout { display: grid; grid-template-columns: 190px 1fr; gap: 0; border: 1px solid var(--line); border-radius: var(--radius); overflow: hidden; background: var(--surface); }
      .helpNav { border-right: 1px solid var(--line); background: var(--surface); display: flex; flex-direction: column; }
      .helpNavItem { display: block; width: 100%; padding: 11px 16px; font-size: 13px; font-weight: 600; color: var(--ink) !important; cursor: pointer; border: none !important; border-bottom: 1px solid var(--line) !important; background: var(--surface) !important; border-radius: 0 !important; box-shadow: none !important; text-align: left; transition: background .12s, color .12s; }
      .helpNavItem:last-child { border-bottom: none !important; }
      .helpNavItem:hover { background: rgba(21,122,110,.06) !important; color: var(--accent) !important; }
      .helpNavItem.active { background: var(--accent) !important; color: #fff !important; font-weight: 700; }
      .helpNavDivider { display: none; }
      .helpContent { padding: 20px; overflow-y: auto; }
      @media(max-width:700px){ .helpLayout { grid-template-columns: 1fr; } .helpNav { flex-direction: row; flex-wrap: wrap; border-right: none; border-bottom: 1px solid var(--line); } .helpNavItem { border-bottom: none !important; border-right: 1px solid var(--line) !important; } .helpNavItem.active { border-bottom: 2px solid var(--accent) !important; } }
      header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }
      header > div { flex: 1; min-width: 0; }
      .snsCard { border: 1.5px solid var(--line); border-radius: 10px; padding: 16px; margin-bottom: 12px; background: var(--surface-2); }
      .snsCardHead { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
      .snsCardTitle { font-weight: 700; font-size: 14px; display: flex; align-items: center; gap: 8px; }
      button:not(.se-btn):not([class*="kuro"]), .button { border: 1px solid var(--accent); background: var(--accent); color: #fff; border-radius: 8px; padding: 10px 14px; font: inherit; font-weight: 750; cursor: pointer; box-shadow: none; }
      button:not(.se-btn):not([class*="kuro"]):hover, .button:hover { filter: brightness(0.97); }
      button:not(.se-btn):disabled { cursor: not-allowed; opacity: 0.48; }
      button.secondary:not(.se-btn), .button.secondary { background: var(--surface-2); color: var(--ink); border-color: var(--line); box-shadow: none; }
      button.danger:not(.se-btn) { background: var(--danger); border-color: var(--danger); }
      button.danger-soft:not(.se-btn) { background: rgba(239,68,68,.12); color: var(--danger); border-color: rgba(239,68,68,.3); box-shadow: none; }
      button.danger-soft:not(.se-btn):hover { background: rgba(239,68,68,.2); border-color: rgba(239,68,68,.5); }
      button.artModeBtn { font-size: 11px !important; padding: 4px 10px !important; white-space: nowrap; min-width: 68px; }
      .toolbar { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }
      .headerTools { display: flex; gap: 10px; align-items: center; justify-content: flex-end; }
      .localeSelect { width: auto; min-width: 120px; }
      .tableScroll { width: 100%; border: 1px solid var(--line); border-radius: var(--radius); background: var(--surface); overflow: hidden; }
      .tableScroll table { border: 0; border-radius: 0; width: 100%; }
      .tableScroll td.flexible, .tableScroll th.flexible { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 0; }
      table { width: 100%; border-collapse: collapse; table-layout: auto; background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius); overflow: hidden; }
      th, td { padding: 12px 14px; border-bottom: 1px solid var(--line); text-align: left; font-size: 14px; vertical-align: middle; overflow-wrap: anywhere; word-break: break-word; }
      th { background: var(--surface-2); color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.06em; white-space: nowrap; width: 1%; }
      tr:last-child td { border-bottom: 0; }
      .tableCompact td:not(.flexible), .tableCompact th:not(.flexible) { width: 1%; white-space: nowrap; }
      .tableCompact td.flexible, .tableCompact th.flexible { width: auto; }
      .badge { display: inline-flex; padding: 4px 9px; border-radius: 999px; background: var(--accent-soft); color: var(--accent-2); font-size: 12px; font-weight: 700; }
      .notice { border: 1px solid var(--line); background: var(--surface-2); padding: 12px 14px; border-radius: 10px; margin-bottom: 18px; }
      .toastWrap { position: fixed; bottom: 24px; right: 24px; z-index: 9000; display: flex; flex-direction: column; gap: 8px; pointer-events: none; }
      .toastItem { pointer-events: auto; padding: 10px 16px; border-radius: 10px; font-size: 13px; font-weight: 600; max-width: 320px; box-shadow: 0 4px 16px rgba(0,0,0,.18); animation: fadeIn .15s ease; background: var(--surface-2); color: var(--ink); border: 1px solid var(--line); }
      .toastItem.error { background: #2d1a1a; color: #f87171; border-color: #7f1d1d; }
      .toastItem.success { background: #162416; color: #4ade80; border-color: #14532d; }
      .callout { position: fixed; z-index: 9100; padding: 8px 12px; border-radius: 8px; font-size: 12px; font-weight: 600; max-width: 260px; box-shadow: 0 4px 14px rgba(0,0,0,.22); animation: fadeIn .12s ease; pointer-events: none; background: var(--ink); color: var(--bg); }
      .callout.error { background: #7f1d1d; color: #fca5a5; }
      .callout::before { content: ''; position: absolute; top: -6px; left: 16px; width: 10px; height: 10px; transform: rotate(45deg); background: inherit; }
      .callout.above::before { top: auto; bottom: -6px; }
      .error { border-left: 4px solid var(--danger); background: color-mix(in srgb, var(--danger) 10%, transparent); color: var(--danger); }
      .pageLead { margin: 7px 0 0; color: var(--muted); font-size: 14px; max-width: 720px; }
      .stat { display: grid; gap: 8px; min-height: 132px; }
      .statValue { font-size: 34px; line-height: 1; font-weight: 800; letter-spacing: -0.02em; color: var(--heading); }
      .statLabel { color: var(--muted); font-size: 13px; font-weight: 600; }
      .split { display: grid; grid-template-columns: minmax(0, 2fr) minmax(0, 1fr); gap: 18px; align-items: start; }
      .emptyState { display: grid; place-items: center; min-height: 220px; border: 1px dashed var(--line-strong); border-radius: 12px; color: var(--muted); background: var(--surface-2); text-align: center; padding: 24px; }
      .mediaGrid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 14px; }
      .mediaTile { aspect-ratio: 4 / 3; border: 1px solid var(--line); border-radius: 12px; background: var(--surface-2); display: grid; place-items: center; color: var(--muted); font-size: 13px; }
      .workflow { display: grid; gap: 12px; }
      .workflowItem { display: grid; grid-template-columns: 30px 1fr; gap: 12px; align-items: start; }
      .workflowNo { display: grid; place-items: center; width: 30px; height: 30px; border-radius: 8px; background: var(--surface-3); font-weight: 800; color: var(--heading); }
      .toggleRow { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 12px; border: 1px solid var(--line); border-radius: 10px; background: var(--surface-2); }
      .toggle { appearance: none; width: 46px; height: 28px; border-radius: 999px; border: 1px solid var(--line-strong); background: var(--surface-3); position: relative; cursor: pointer; transition: all 160ms ease; }
      .toggle::after { content: ""; position: absolute; top: 3px; left: 3px; width: 20px; height: 20px; border-radius: 50%; background: var(--muted); transition: all 160ms ease; }
      .toggle:checked { background: var(--accent); border-color: var(--accent); }
      .toggle:checked::after { left: 21px; background: #fff; }
      .tokenBox { padding: 12px; border: 1px dashed var(--line-strong); border-radius: 10px; background: var(--surface-2); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; overflow-wrap: anywhere; }
      .tokenList { display: grid; gap: 6px; }
      .tokenRow { display: grid; grid-template-columns: minmax(0, 1fr) auto auto; gap: 8px; align-items: center; border: 1px solid var(--line); border-radius: 10px; padding: 6px 10px; background: var(--surface-2); }
      .tokenRow button { padding: 4px 10px; font-size: 12px; }
      .tokenMeta { font-size: 11px; color: var(--muted); }
      .tokenLabel { font-size: 15px; font-weight: 700; color: var(--ink); }
      .tokenHelp { font-size: 12px; color: var(--muted); margin-top: 4px; }
      .tokenOutputRow { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; align-items: center; }
      .categoryToolbar { display: flex; align-items: center; justify-content: space-between; gap: 10px; flex-wrap: wrap; }
      .categoryHint { font-size: 13px; color: var(--muted); margin: -6px 0 0; }
      .articleMetaSplit { display: grid; grid-template-columns: minmax(0, 2fr) minmax(0, 1fr); gap: 16px; align-items: start; }
      .articleMetaSplit textarea { min-height: 92px; font-family: inherit; }
      .editorTabs { display: inline-flex; gap: 8px; margin-bottom: 10px; }
      .editorTab {
        border: 1px solid var(--line);
        background: var(--surface-2);
        color: var(--muted);
        border-radius: 8px;
        padding: 8px 12px;
        font-size: 13px;
        font-weight: 700;
        cursor: pointer;
      }
      .editorTab.active {
        background: var(--accent-soft);
        color: var(--ink);
        border-color: color-mix(in srgb, var(--accent) 42%, var(--line));
      }
      .sourceView {
        min-height: 340px;
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      }
      .editorPane[hidden] { display: none !important; }
      .publishPickerRow { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; align-items: center; }
      .publishPickerButton { min-width: 48px; padding: 10px 12px; }
      .articleSaveDock {
        position: sticky;
        bottom: 12px;
        z-index: 30;
        display: flex;
        justify-content: flex-end;
        padding: 10px;
        margin-top: 8px;
        border: 1px solid var(--line);
        border-radius: 16px;
        background: color-mix(in srgb, var(--surface) 80%, transparent);
        box-shadow: var(--shadow);
        backdrop-filter: blur(12px);
      }
      .setup { max-width: 1080px; }
      .setupHero { display: grid; gap: 10px; margin-bottom: 18px; padding: 24px; border-radius: 16px; background: linear-gradient(135deg, #1e293b 0%, var(--bg) 100%); color: var(--ink); box-shadow: var(--shadow); border: 1px solid var(--line); }
      [data-theme="dark"] .setupHero { background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); }
      .setupHero h2 { font-size: 32px; margin: 0; color: var(--heading); }
      .setupHero p { max-width: 720px; margin: 0; color: var(--muted); }
      .setupLayout { display: grid; grid-template-columns: minmax(0, 1fr); gap: 14px; align-items: start; }
      .setupAside { background: var(--surface-2); color: var(--ink); padding: 20px; border-radius: 12px; border: 1px solid var(--line); }
      .setupAside .sectionLabel { color: var(--heading); }
      .setupAside ol { margin: 0; padding-left: 20px; color: var(--muted); }
      .setupAside li { margin: 8px 0; }
      .setupOtpNotice { border: 2px solid var(--danger); border-radius: 10px; padding: 12px; background: color-mix(in srgb, var(--danger) 8%, transparent); color: var(--danger); font-size: 13px; line-height: 1.6; font-weight: 600; }
      .sectionLabel { color: var(--accent-2); font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.1em; }
      code { padding: 2px 6px; border-radius: 6px; background: var(--surface-3); color: var(--accent-2); font-family: ui-monospace, monospace; font-size: 0.9em; }
      .tableScroll code {
        color: var(--ink);
        background: color-mix(in srgb, var(--surface-2) 78%, var(--accent) 22%);
        border: 1px solid var(--line-strong);
        font-weight: 700;
      }
      .rowActions { display: flex; gap: 6px; align-items: center; justify-content: flex-end; white-space: nowrap; flex-wrap: nowrap; }
      .buildProgress { position: fixed; inset: 0; background: rgba(0,0,0,.55); display: flex; align-items: center; justify-content: center; z-index: 9000; }
      .buildProgressCard { background: var(--surface); border-radius: 16px; padding: 28px 28px 24px; width: min(520px, calc(100vw - 32px)); box-shadow: 0 24px 64px rgba(0,0,0,.28); display: flex; flex-direction: column; gap: 16px; }
      .buildProgressBar { height: 8px; border-radius: 4px; background: var(--line); overflow: hidden; }
      .buildProgressFill { height: 100%; background: var(--accent); border-radius: 4px; transition: width .15s linear; }
      .buildLog { font-size: 11px; font-family: ui-monospace, monospace; max-height: 200px; overflow-y: auto; background: var(--surface-2); border-radius: 8px; padding: 8px 10px; border: 1px solid var(--line); display: flex; flex-direction: column; gap: 2px; }
      .buildLogLine { display: flex; gap: 6px; align-items: baseline; line-height: 1.5; }
      .buildLogLine.built { color: var(--accent); }
      .buildLogLine.skipped { color: var(--muted); }
      .buildLogLine.error { color: var(--danger); }
      .imgLightbox { position: fixed; inset: 0; background: rgba(0,0,0,.82); display: flex; align-items: center; justify-content: center; z-index: 9100; cursor: zoom-out; padding: 20px; box-sizing: border-box; }
      .imgLightboxInner { position: relative; max-width: min(90vw, 1200px); max-height: 90vh; display: flex; flex-direction: column; align-items: flex-end; gap: 10px; }
      .imgLightboxInner img { max-width: 100%; max-height: calc(90vh - 52px); object-fit: contain; border-radius: 8px; box-shadow: 0 8px 48px rgba(0,0,0,.5); display: block; }
      .imgLightboxClose { background: var(--accent); color: #fff; border: none; border-radius: 8px; padding: 8px 22px; font-size: 14px; font-weight: 700; cursor: pointer; box-shadow: 0 2px 8px rgba(0,0,0,.3); }
      .rowActions button { padding: 6px 10px !important; font-size: 12px; white-space: nowrap; flex-shrink: 0; }
      table th:last-child, table td:last-child { width: 1%; white-space: nowrap; padding-right: 12px; }
      .credit { margin-top: 24px; color: var(--muted); font-size: 12px; font-weight: 500; }
      .dropZone { border: 2px dashed var(--accent); border-radius: var(--radius); padding: 32px 20px; text-align: center; cursor: pointer; transition: background 0.15s; color: var(--muted); }
      .dropZone:hover, .dropZone.over { background: rgba(21,122,110,.08); border-color: var(--accent); color: var(--accent); }
      .dropZoneIcon { font-size: 36px; margin-bottom: 8px; }
      .dropZoneLead { font-size: 14px; margin: 0 0 12px; }
      .uploadQueue { display: grid; gap: 8px; margin-top: 12px; }
      .uploadItem { display: flex; align-items: center; gap: 10px; padding: 8px 12px; border-radius: 10px; background: var(--surface-2); border: 1px solid var(--line); font-size: 13px; }
      .uploadThumb { width: 48px; height: 48px; object-fit: cover; border-radius: 6px; flex-shrink: 0; background: var(--line); }
      .uploadThumbIcon { width: 48px; height: 48px; display: flex; align-items: center; justify-content: center; font-size: 24px; flex-shrink: 0; }
      .uploadInfo { flex: 1; min-width: 0; }
      .uploadName { font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
      .uploadMeta { color: var(--muted); font-size: 11px; margin-top: 2px; }
      .uploadStatus { font-size: 12px; font-weight: 600; white-space: nowrap; }
      .uploadStatus.ok { color: var(--accent); }
      .uploadStatus.err { color: var(--danger); }
      .storageGrid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
      @media(max-width:700px){ .storageGrid { grid-template-columns: 1fr 1fr; } }
      .storageCard { background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius); padding: 16px; display: flex; flex-direction: column; align-items: center; gap: 10px; }
      .storageCard.storage-alert { border-color: var(--danger); background: rgba(220,38,38,0.07); }
      .storageCard.unavailable { opacity: 0.45; filter: grayscale(1); pointer-events: none; }
      .storageUnavailable { font-size: 11px; font-weight: 700; color: var(--muted); background: var(--surface-3); border: 1px solid var(--line); border-radius: 6px; padding: 2px 8px; margin-bottom: -4px; text-align: center; }
      .storageCardTitle { font-weight: 700; font-size: 13px; color: var(--muted); text-align: center; }
      .navAlertDot { position: absolute; top: 7px; right: 8px; width: 8px; height: 8px; border-radius: 50%; background: var(--danger); pointer-events: none; }
      .dashStatChip { display:inline-flex; align-items:center; gap:6px; background:var(--surface-2); border:1px solid var(--line); border-radius:8px; padding:6px 14px; font-size:13px; }
      .dashStatChip strong { font-size:20px; font-weight:800; color:var(--accent); }
      .versionRow { display:flex; justify-content:space-between; align-items:center; font-size:13px; padding:3px 0; }
      .versionLabel { color:var(--muted); font-size:12px; }
      .versionVal { font-weight:700; font-size:15px; }
      .versionVal.has-update { color:var(--danger); }
      .toggleSwitch { position:relative; display:inline-block; width:36px; height:20px; flex-shrink:0; }
      .toggleSwitch input { opacity:0; width:0; height:0; position:absolute; }
      .toggleSlider { position:absolute; cursor:pointer; inset:0; background:#ccc; border-radius:20px; transition:.2s; }
      .toggleSlider:before { position:absolute; content:""; height:14px; width:14px; left:3px; bottom:3px; background:#fff; border-radius:50%; transition:.2s; }
      input:checked + .toggleSlider { background:var(--accent); }
      input:checked + .toggleSlider:before { transform:translateX(16px); }
      .updateBtnWrap { position:relative; display:inline-block; width:100%; }
      .updateBadge { position:absolute; top:-4px; right:-4px; min-width:8px; height:8px; border-radius:50%; background:var(--danger); pointer-events:none; }
      .pieWrap { position: relative; width: 100px; height: 100px; flex-shrink: 0; }
      .pieWrap svg { width: 100%; height: 100%; transform: rotate(-90deg); }
      .pieBg { fill: none; stroke: var(--line); stroke-width: 14; }
      .pieArc { fill: none; stroke-width: 14; stroke-linecap: round; transition: stroke-dasharray 0.8s ease; }
      .pieArc.ok { stroke: var(--accent); }
      .pieArc.warn { stroke: var(--accent-3); }
      .pieArc.danger { stroke: var(--danger); }
      .piePct { position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; font-weight: 800; font-size: 17px; line-height: 1; }
      .piePctSub { font-size: 10px; font-weight: 600; color: var(--muted); margin-top: 2px; }
      .storageDetail { font-size: 11px; color: var(--muted); text-align: center; line-height: 1.6; }
      .mobileNav { display: none; }
      .mobileNavBar { display: none; }
      .balloon {
        position: absolute;
        top: -10px;
        left: 50%;
        transform: translate(-50%, -100%);
        background: var(--danger);
        color: #fff;
        padding: 6px 12px;
        border-radius: 8px;
        font-size: 13px;
        font-weight: 700;
        white-space: nowrap;
        z-index: 1000;
        pointer-events: none;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        animation: balloon-fade 240ms cubic-bezier(0.16, 1, 0.3, 1);
      }
      .balloon::after {
        content: "";
        position: absolute;
        top: 100%;
        left: 50%;
        margin-left: -6px;
        border-width: 6px;
        border-style: solid;
        border-color: var(--danger) transparent transparent transparent;
      }
      .popupBackdrop {
        position: fixed;
        inset: 0;
        z-index: 2200;
        background: rgba(15, 23, 42, 0.45);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: clamp(8px, 3vw, 24px);
        overflow-y: auto;
      }
      .popupCard {
        width: min(92vw, calc(100% - 16px));
        max-width: 92vw;
        max-height: calc(100vh - clamp(32px, 6vh, 80px));
        overflow-y: auto;
        background: var(--surface);
        border: 1px solid var(--line);
        border-radius: 12px;
        box-shadow: var(--shadow);
        padding: clamp(14px, 3vw, 24px);
        display: grid;
        gap: 14px;
      }
      .popupTitle { margin: 0; font-size: 18px; color: var(--ink); }
      .popupBody { color: var(--muted); font-size: 14px; line-height: 1.7; overflow-x: auto; word-break: break-word; }
      .popupBody table { word-break: normal; }
      .popupBody td, .popupBody th { word-break: break-word; white-space: normal; }
      .popupActions { display: flex; justify-content: flex-end; gap: 8px; flex-wrap: wrap; }
      /* Site-text KuroEditor dialog: near-fullscreen + internal scroll. Scoped to
         .popupCard.kuroDlg only — does NOT affect the article editor. */
      .popupBackdrop:has(.popupCard.kuroDlg) { padding: clamp(6px, 1ch, 14px); }
      .popupCard.kuroDlg { width: 66vw; max-width: none; height: 100%; max-height: none; overflow: hidden; display: flex; flex-direction: column; }
      .popupCard.kuroDlg #entryDialogForm { flex: 1; min-height: 0; display: flex; flex-direction: column; gap: 10px; }
      .popupCard.kuroDlg .popupBody { flex: 1; min-height: 0; overflow: hidden; display: flex; }
      .popupCard.kuroDlg .popupBody > .stack { flex: 1; min-height: 0; display: flex; flex-direction: column; gap: 8px; }
      .popupCard.kuroDlg .kuro-editor { flex: 1; min-height: 0; }
      /* Broken media reference callout in the site-text list (near its row). */
      .mediaRefError { margin-top: 6px; border: 1.5px solid var(--danger); background: rgba(220,38,38,.07); color: var(--danger); border-radius: 6px; padding: 6px 10px; font-size: 12px; line-height: 1.6; white-space: normal; }
      .mediaRefError code { background: rgba(220,38,38,.12); padding: 1px 5px; border-radius: 4px; }
      .mediaRefHint { color: var(--muted); margin-top: 3px; font-size: 11px; }
      /* KuroEditor floating popups are appended to <body> at a low z-index (z-40),
         so inside the site-text dialog they fall BEHIND the backdrop (z-2200) and
         become invisible (image-settings menu, roundbox menu, media/emoji/table…).
         Lift them above the dialog. */
      .kuro-image-menu, .kuro-roundbox-menu, .kuro-table-menu, .kuro-table-inserter,
      .kuro-line-popm, .kuro-emoji-panel, .kuro-media-dialog, .kuro-mmenu { z-index: 2300 !important; }
      .panelHead { display: flex; align-items: center; justify-content: space-between; gap: 12px; }
      .panelHead h3 { margin: 0; }
      .panelHead .toolbar { margin: 0; }
      @keyframes balloon-fade {
        from { opacity: 0; transform: translate(-50%, -80%) scale(0.95); }
        to { opacity: 1; transform: translate(-50%, -100%) scale(1); }
      }
      label { position: relative; overflow: visible !important; }
      @media (max-width: 860px) {
        .app { display: block; }
        aside { display: none; }
        .sidebarResizer { display: none; }
        main { padding: 22px 16px 96px; max-width: none; min-height: 100vh; }
        header { align-items: flex-start; flex-direction: column; gap: 14px; margin-bottom: 22px; }
        h2 { font-size: 28px; }
        .grid, .grid.two, .grid.four, .split, .setupLayout, .articleMetaSplit { grid-template-columns: 1fr; }
        .setupHero { margin-bottom: 12px; padding: 20px; border-radius: 12px; }
        .setupHero h2 { font-size: 26px; line-height: 1.2; }
        .setupAside { display: none; }
        .panel { padding: 16px; }
        .mediaGrid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
        .licenseBox { max-height: 260px; font-size: 11px; }
        .toolbar { flex-wrap: wrap; }
        .toolbar input { min-width: 0; }
        /* Settings tabs: scrollable on mobile */
        .settingsTabBar { overflow-x: auto; overflow-y: hidden; -webkit-overflow-scrolling: touch; flex-wrap: nowrap; padding-bottom: 0; }
        .settingsTab { font-size: 12px; padding: 7px 12px; white-space: nowrap; flex-shrink: 0; }
        /* Import screen grids */
        #strapiImportSection div[style*="grid-template-columns:1fr 1fr"] { grid-template-columns: 1fr !important; }
        /* Article editor */
        .articleTopGrid { grid-template-columns: 1fr; }
        .articleCoverArea { border-right: none; border-bottom: 1px solid var(--line); }
        .articleCoverBox { aspect-ratio: 3/1; }
        button.artModeBtn { font-size: 10px !important; padding: 3px 8px !important; min-width: 56px; }
        /* Color rows */
        .colorRows { gap: 12px; }
        .colorItem { flex-direction: row; align-items: center; justify-content: space-between; }
        /* Build bar */
        .buildBar { flex-wrap: wrap; gap: 8px; }
        /* SNS card */
        .snsCard { padding: 14px; }
        .snsCardHead { flex-direction: column; align-items: flex-start; gap: 8px; }
        /* Help layout */
        .helpLayout { grid-template-columns: 1fr; }
        .helpNav { flex-direction: row; flex-wrap: wrap; border-right: none; border-bottom: 1px solid var(--line); }
        /* Modal: align to top on mobile to stay clear of bottom nav */
        .popupBackdrop { justify-content: flex-start; padding-top: 16px; }
        .popupCard { width: calc(100vw - 24px) !important; margin: 0 auto; max-height: calc(100svh - 128px); border-radius: 12px; }
        .mobileNav {
          display: flex;
          gap: 6px;
          position: fixed;
          left: 10px;
          right: 10px;
          bottom: 10px;
          z-index: 40;
          padding: 8px 8px 14px;
          border: 1px solid var(--line);
          border-radius: 20px;
          background: color-mix(in srgb, var(--surface) 85%, transparent);
          box-shadow: var(--shadow);
          backdrop-filter: blur(12px);
          overflow-x: auto;
          scrollbar-width: none;
        }
        .mobileNav::-webkit-scrollbar { display: none; }
        /* Always-visible scrollbar track inside nav bottom padding */
        .mobileNavBar {
          display: block;
          position: fixed;
          left: 26px; right: 26px; bottom: 14px;
          height: 4px;
          background: var(--line);
          border-radius: 2px;
          z-index: 41;
          pointer-events: none;
        }
        .mobileNavThumb {
          position: absolute;
          top: 0; height: 100%;
          background: var(--accent);
          border-radius: 2px;
          will-change: transform;
        }
        .mobileNav a {
          display: grid;
          place-items: center;
          gap: 4px;
          flex: 0 0 68px;
          min-height: 58px;
          padding: 8px 6px;
          border-radius: 12px;
          color: var(--nav-link);
          font-size: 11px;
          font-weight: 600;
          text-align: center;
        }
        .mobileNav a svg { width: 18px; height: 18px; }
        .mobileNav a.active { background: var(--nav-active-bg); color: var(--nav-active-fg); }
        .mobileNav a.active svg { color: var(--heading); }
      }
      @media (max-width: 480px) {
        main { padding: 16px 12px 96px; }
        .panel { padding: 14px; }
        h2 { font-size: 22px; }
        .mediaGrid { grid-template-columns: 1fr; }
        .settingsTab { font-size: 11px; padding: 6px 10px; }
        header { gap: 10px; margin-bottom: 16px; }
        .popupCard { border-radius: 12px; }
      }
      /* ── KuroEditor style isolation ─────────────────────────────── */
      /* Revert admin broad-selector styles for specific element types
         inside KuroEditor. Only touch the element types that admin
         explicitly overrides (h2/h3, form controls, label, a).
         Structural flex/overflow properties on .kuro-* divs are left
         alone so KE's own @layer components layout is unaffected.
         Buttons are already handled by :not([class*="kuro"]) above. */
      .kuro-editor h1, .kuro-editor h2, .kuro-editor h3,
      .kuro-editor h4, .kuro-editor h5 { all: revert-layer; }
      .kuro-editor input, .kuro-editor select,
      .kuro-editor textarea { all: revert-layer; }
      .kuro-editor label { all: revert-layer; }
      .kuro-editor a { all: revert-layer; }
      /* Bare-element admin rules in @layer kurocms (the top layer) otherwise win
         over KuroEditor's lower-layer content styles and leak into the editor.
         The admin table rule (table-layout:auto; overflow:hidden) made content
         tables use auto layout and clip their right columns (public is fine — it
         has no admin host CSS); code, aside, header, main would likewise
         restyle/break imported content using those tags. Revert every bare
         element type the admin styles so the editor's own styles apply. (h1-h5,
         form controls, label, a are handled above.) */
      .kuro-editor table, .kuro-editor thead, .kuro-editor tbody,
      .kuro-editor tr, .kuro-editor td, .kuro-editor th,
      .kuro-editor code, .kuro-editor aside,
      .kuro-editor header, .kuro-editor main { all: revert-layer; }
      /* Force fit explicitly (class-independent): revert-layer only restores
         table-layout:fixed when the table still has its .kuro-table class, which
         the contenteditable DOM may drop. This guarantees editor content tables
         fit the pane regardless of class, so right columns aren't clipped. */
      .kuro-editor table {
        table-layout: fixed;
        width: 100%;
        max-width: 100%;
        overflow: visible;
        border: 0;
        background: transparent;
        border-radius: 0;
      }
      /* Admin data-table rules leak into editor CONTENT tables. In particular the
         action-column rule (table td:last-child / th:last-child -> width:1%;
         white-space:nowrap, defined above) out-specifies .kuro-editor td{all:revert-layer}
         because the :last-child pseudo-class makes it (0,1,2) vs (0,1,1). That collapses
         an imported table's last column to width:1% (so the first column fills ~99% of
         the row) and forces white-space:nowrap (long CJK text can't wrap -> overflows
         right). Restore content-cell behavior with selectors that out-specify the leak. */
      .kuro-editor td, .kuro-editor th,
      .kuro-editor td:first-child, .kuro-editor th:first-child,
      .kuro-editor td:last-child, .kuro-editor th:last-child {
        width: auto;
        white-space: normal;
        word-break: break-word;
        overflow-wrap: anywhere;
      }

      /* ── KuroEditor expand to content (no internal scroll) ───────── */
      /* Override KE's own overflow:hidden / flex:1 layout so the
         editor grows with content instead of clipping at a fixed height.
         The page itself scrolls; the editor should never scroll internally. */
      .articleBodyWrap .kuro-editor { overflow: visible; }
      .articleBodyWrap .kuro-body { overflow: visible; flex: none; height: auto; }
      .articleBodyWrap .kuro-pane { overflow: visible; flex: 1; min-width: 0; }
      .articleBodyWrap .kuro-pane__wysiwyg { overflow: visible; flex: none; height: auto; min-height: 400px; }
      } /* end @layer kurocms */

    </style>
    <link rel="stylesheet" id="ke-css" href="${base}/_admin/ke.${KE_VERSION}.css" />
  </head>
  <body>
    <div class="app">
      <aside>
        <div class="brand">
          <div class="brandMark"></div>
          <div>
            <h1>Kuro<span class="brandAccent">CMS</span></h1>
            <div class="brandSub"></div>
          </div>
        </div>
        <div class="sidebarBody">
          <nav class="sidebarNav" id="sidebarNav">
            <a href="${accessAdminUrl}" data-nav="/">Dashboard</a>
            <a href="${accessAdminUrl}/articles" data-nav="/articles">Articles</a>
            <a href="${accessAdminUrl}/articles/new" data-nav="/articles/new">New Article</a>
          </nav>
        </div>
        <nav class="sidebarNav sidebarFooter" id="sidebarFooterNav"></nav>
      </aside>
      <div class="sidebarResizer" id="sidebarResizer" title="Drag to resize"></div>
      <main id="app"><div class="initialLoader"><div class="initialLoaderSpinner"></div><p class="initialLoaderLabel">Now Loading...</p></div></main>
      <nav class="mobileNav" id="mobileNav" aria-label="Primary navigation"></nav>
      <div class="mobileNavBar" id="mobileNavBar" aria-hidden="true" style="display:none"><div class="mobileNavThumb" id="mobileNavThumb"></div></div>
    </div>
    <script>window.__ACCESS_ADMIN_URL__ = ${JSON.stringify(accessAdminUrl)};</script>
    <script src="${base}/_admin/ke.${KE_VERSION}.js"></script>
    <script src="${base}/_admin/admin-app.${ADMIN_APP_HASH}.js"></script>
  </body>
</html>`;
}
